# model config
model_params:
  embed_dim: 128
  num_heads: 4
  num_layers: 1
  num_classes: 5
  pooling_head: 4
  dropout: 0.3
  max_seq_length: 8196

max_channels: 4
context: -1
seed: 42
model: 'SleepEventLSTMClassifier'
dataset: 'mesa'
batch_size: 16
epochs: 2
lr: 0.001
num_workers: 8

# make sure to change this path to your local paths. Also, look at README.md for what labels_path should contain
data_path: '/scratch/users/rthapa84/psg_fm/data/data_new_128/'
model_path: '../checkpoints/SetTransformer/leave_one_out_128_patch_size_3840'
split_path: '../configs/dataset_split.json'
labels_path: '/oak/stanford/groups/jamesz/rthapa84/psg_fm/10_14_28/annotations/sleep_stages'
save_iter: 1000
eval_iter: 1000
log_interval: 10
accumulation_steps: 16
use_wandb: false

# dataloader configs
max_files: 100
sampling_freq: 128

channel_like: ["BAS", "RESP", "EKG", "EMG"]

